# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 The Foundation for Public Code <info@publiccode.net>

title: The Governance Game
version: 1.0.1

remote_theme: publiccodenet/jekyll-theme
include:
  - "index.md"

toc: false

baseurl: /
